# read_kaldi_output.py
# Amir Harati May 2019
"""
    read files generated by Kaldi scrip.
    each line in file looks like: key [values]
"""
def read_kaldi_output(fname):
    lines = [line.strip() for line in open(fname)]
    keys = []
    vals = []
    for line in lines:
        parts = line.split()
        key = parts[0]
        val = []
        for p in parts[2:-1]:
            val.append(float(p))
        keys.append(key)
        vals.append(val)
   
    return keys, vals

#read_kaldi_output("./x1.txt")